FROM python:3.11-slim

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# System-Abhängigkeiten
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir streamlit requests

# Modell-Preloading
#RUN --mount=type=secret,id=HF_TOKEN \
#    HF_TOKEN=$(cat /run/secrets/HF_TOKEN) python -c \
#    "from langchain_community.embeddings import FastEmbedEmbeddings; \
#    FastEmbedEmbeddings(model_name='sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2')"

COPY app.py .

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
